spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=findhabitat;encrypt=true;trustServerCertificate=true;
spring.datasource.username=findhabitat_user
spring.datasource.password=""

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ddl-auto option is convenient for development, but should be disabled in production
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
server.port=8081

